# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-02 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('texts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textword',
            name='user_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserWord'),
        ),
        migrations.AddField(
            model_name='text',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='text',
            name='words',
            field=models.ManyToManyField(blank=True, through='texts.TextWord', to='users.UserWord'),
        ),
        migrations.AlterUniqueTogether(
            name='textword',
            unique_together=set([('text', 'user_word')]),
        ),
    ]
