export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const ADD_TEXT_REQUEST = 'ADD_TEXT_REQUEST';
export const ADD_TEXT_SUCCESS = 'ADD_TEXT_SUCCESS';
export const ADD_TEXT_FAILURE = 'ADD_TEXT_FAILURE';

export const FETCH_TEXT_LIST_REQUEST = 'FETCH_TEXT_LIST_REQUEST';
export const FETCH_TEXT_LIST_SUCCESS = 'FETCH_TEXT_LIST_SUCCESS';
export const FETCH_TEXT_LIST_FAILURE = 'FETCH_TEXT_LIST_FAILURE';

export const FETCH_TEXT_REQUEST = 'FETCH_TEXT_REQUEST';
export const FETCH_TEXT_SUCCESS = 'FETCH_TEXT_SUCCESS';
export const FETCH_TEXT_FAILURE = 'FETCH_TEXT_FAILURE';

export const FETCH_WORD_LIST_REQUEST = 'FETCH_WORD_LIST_REQUEST';
export const FETCH_WORD_LIST_SUCCESS = 'FETCH_WORD_LIST_SUCCESS';
export const FETCH_WORD_LIST_FAILURE = 'FETCH_WORD_LIST_FAILURE';
